[package]
name = "hello_world"
version = "0.1.0"
authors = ["Raghavendra Balgi <rkbalgi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
hex = "0.4.2"
byteorder = "1.3.4"